---
abstract: 'Pluggable IRC bot (cobalt2)'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cobalt
provides:
  Cobalt::Conf:
    file: lib/Cobalt/Conf.pm
    version: 0.10
  Cobalt::Core:
    file: lib/Cobalt/Core.pm
    version: 2.00_7
  Cobalt::IRC:
    file: lib/Cobalt/IRC.pm
    version: 0.10
  Cobalt::Lang:
    file: lib/Cobalt/Lang.pm
    version: 0.12
  Cobalt::Plugin::Alarmclock:
    file: lib/Cobalt/Plugin/Alarmclock.pm
    version: 0.10
  Cobalt::Plugin::Auth:
    file: lib/Cobalt/Plugin/Auth.pm
    version: 0.10
  Cobalt::Plugin::Calc:
    file: lib/Cobalt/Plugin/Extras/Calc.pm
    version: 0
  Cobalt::Plugin::Extras::Debug:
    file: lib/Cobalt/Plugin/Extras/Debug.pm
    version: 0.001
  Cobalt::Plugin::Extras::Ignore:
    file: lib/Cobalt/Plugin/Extras/Ignore.pm
    version: 0.10
  Cobalt::Plugin::Extras::TempConv:
    file: lib/Cobalt/Plugin/Extras/TempConv.pm
    version: 1.0
  Cobalt::Plugin::FloodProtect:
    file: lib/Cobalt/Plugin/FloodProtect.pm
    version: 0.10
  Cobalt::Plugin::Games:
    file: lib/Cobalt/Plugin/Games.pm
    version: 0.10
  Cobalt::Plugin::Games::Dice:
    file: lib/Cobalt/Plugin/Games/Dice.pm
    version: 0.01
  Cobalt::Plugin::Games::Magic8:
    file: lib/Cobalt/Plugin/Games/Magic8.pm
    version: 0.01
  Cobalt::Plugin::Games::RockPaperScissors:
    file: lib/Cobalt/Plugin/Games/RockPaperScissors.pm
    version: 0.01
  Cobalt::Plugin::Games::Roulette:
    file: lib/Cobalt/Plugin/Games/Roulette.pm
    version: 0.001
  Cobalt::Plugin::Info3:
    file: lib/Cobalt/Plugin/Info3.pm
    version: 0.10
  Cobalt::Plugin::OutputFilters::StripFormat:
    file: lib/Cobalt/Plugin/OutputFilters/StripFormat.pm
    version: 0.10
  Cobalt::Plugin::PluginMgr:
    file: lib/Cobalt/Plugin/PluginMgr.pm
    version: 0.10
  Cobalt::Plugin::RDB:
    file: lib/Cobalt/Plugin/RDB.pm
    version: 0.10
  Cobalt::Plugin::Rehash:
    file: lib/Cobalt/Plugin/Rehash.pm
    version: 0.10
  Cobalt::Plugin::Version:
    file: lib/Cobalt/Plugin/Version.pm
    version: 0.10
  Cobalt::Serializer:
    file: lib/Cobalt/Serializer.pm
    version: 0.12
  Cobalt::Utils:
    file: lib/Cobalt/Utils.pm
    version: 0.14
recommends:
  POE::Component::SSLify: 1.006
  Term::ReadKey: 0
requires:
  Carp: 0
  Crypt::Eksblowfish: 0.003
  Data::Dumper: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 2.00
  File::Slurp: 9999
  File::Spec: 0
  Getopt::Long: 0
  IRC::Utils: 0.12
  JSON: 2.00
  Log::Handler: 0.71
  Moose: 2.00
  MooseX::NonMoose: 0.18
  Object::Pluggable: 1.27
  POE: 1.311
  POE::Component::IRC: 6.75
  POE::Component::Syndicator: 0.06
  Proc::PID::File: 1.26
  YAML::Syck: 1.18
  namespace::autoclean: 0.12
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 2.00_7
